This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./travelintegrationtests.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file travelintegrationtests.acn....done (98 entries accepted, 0 rejected).
Sorting entries....done (645 comparisons).
Generating output file travelintegrationtests.acr....done (70 lines written, 0 warnings).
Output written in travelintegrationtests.acr.
Transcript written in travelintegrationtests.alg.
